import Balance from "@/components/balance/balance";
import Graph from "@/components/graph/graph";
import Head from "next/head";
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-[#F7E9DC] h-screen flex justify-center items-center font-sans">
        <motion.div
          animate={{ x: 0, opacity: 1 }}
          initial={{ x: -200, opacity: 0 }}
          transition={{ type: "spring", damping: 10, stiffness: 70 }}
          className="w-96 max-sm:w-11/12 max-sm:h-2/3 flex gap-6 flex-col h-1/2"
        >
          <Balance />
          <Graph />
        </motion.div>
      </main>
    </>
  );
}
